import { useState } from "react";
import { motion } from "framer-motion";
import {
  Eye, Smartphone, Monitor, Tablet, Code2,
} from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useI18n } from "@/lib/i18n";
import GeneratedPrototype from "./GeneratedPrototype";
import type { AppBlueprint } from "./AIPlannerEngine";

interface AppPreviewProps {
  isGenerated: boolean;
  appName: string;
  blueprint?: AppBlueprint | null;
}

type ViewMode = "desktop" | "tablet" | "mobile";

const viewWidths: Record<ViewMode, string> = {
  desktop: "w-full",
  tablet: "w-[768px] max-w-full",
  mobile: "w-[375px] max-w-full",
};

const AppPreview = ({ isGenerated, appName, blueprint }: AppPreviewProps) => {
  const [viewMode, setViewMode] = useState<ViewMode>("mobile");
  const [showCode, setShowCode] = useState(false);
  const { t } = useI18n();

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="sf-glass rounded-2xl p-6"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Eye className="h-5 w-5 text-accent" />
          <h2 className="text-lg font-semibold text-foreground">
            {t("preview.title")}
          </h2>
          {isGenerated && (
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full sf-gradient-bg text-background">
              LIVE
            </span>
          )}
          <Tooltip>
            <TooltipTrigger>
              <span className="text-xs sf-glass-subtle text-muted-foreground px-2 py-0.5 rounded-full cursor-help">
                ?
              </span>
            </TooltipTrigger>
            <TooltipContent>
              <p className="max-w-xs text-sm">{t("preview.tooltip")}</p>
            </TooltipContent>
          </Tooltip>
        </div>

        <div className="flex items-center gap-1 sf-glass-subtle rounded-lg p-1">
          {([
            { mode: "desktop" as const, icon: Monitor },
            { mode: "tablet" as const, icon: Tablet },
            { mode: "mobile" as const, icon: Smartphone },
          ]).map(({ mode, icon: Icon }) => (
            <button
              key={mode}
              onClick={() => setViewMode(mode)}
              className={`p-2 rounded-md transition-all ${
                viewMode === mode
                  ? "sf-glass-strong text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              <Icon className="h-4 w-4" />
            </button>
          ))}
          <div className="w-px h-5 bg-foreground/20 mx-1" />
          <button
            onClick={() => setShowCode(!showCode)}
            className={`p-2 rounded-md transition-all ${
              showCode
                ? "sf-glass-strong text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <Code2 className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Emulator frame */}
      <div className={`mx-auto transition-all duration-300 ${viewWidths[viewMode]}`}>
        <div className="rounded-[2rem] border-2 border-[hsl(220,20%,22%)] bg-[hsl(220,25%,6%)] p-1.5 shadow-2xl">
          {/* Notch */}
          <div className="flex justify-center mb-[-6px] relative z-10">
            <div className="w-24 h-5 bg-[hsl(220,25%,6%)] rounded-b-xl" />
          </div>

          {/* Screen */}
          <div className="rounded-[1.4rem] overflow-hidden">
            {!isGenerated ? (
              <div className="flex flex-col items-center justify-center h-[500px] bg-[hsl(220,25%,8%)] text-muted-foreground">
                <Smartphone className="h-16 w-16 mb-4 opacity-20" />
                <p className="text-sm">{t("preview.empty")}</p>
                <p className="text-xs mt-1 opacity-60">{t("preview.hint")}</p>
              </div>
            ) : showCode ? (
              <div className="h-[500px] overflow-auto p-4 bg-[hsl(220,25%,6%)] text-[hsl(90,60%,50%)] font-mono text-xs leading-relaxed">
                <pre className="whitespace-pre-wrap">{`// ${appName} — Generated by Sirou Factory
// Functional Prototype — All buttons are interactive

import React, { useState } from 'react';
import { toast } from 'sonner';
import { Camera, MapPin, QrCode } from 'lucide-react';
import { capturePhoto, scanQR } from '@/lib/hardware';

const App: React.FC = () => {
  const [items, setItems] = useState([]);
  const [cart, setCart] = useState(0);

  const handleCamera = async () => {
    const result = await capturePhoto();
    if (result.success) toast.success('Photo captured!');
  };

  const handleGPS = () => {
    navigator.geolocation.getCurrentPosition(
      pos => toast.success(\`📍 \${pos.coords.latitude}\`),
      () => toast.error('GPS denied')
    );
  };

  return (
    <div className="min-h-screen bg-sovereign-dark">
      <header className="sovereign-gradient p-4">
        <h1>${appName}</h1>
      </header>
      {/* Interactive list with state */}
      {/* Hardware buttons: Camera, GPS, QR */}
      {/* Cart with counter */}
      <nav className="bottom-nav">
        <Home /> <Heart /> <Cart badge={cart} />
      </nav>
    </div>
  );
};`}</pre>
              </div>
            ) : (
              <GeneratedPrototype appName={appName} blueprint={blueprint ?? null} />
            )}
          </div>

          {/* Home indicator */}
          <div className="flex justify-center py-2">
            <div className="w-28 h-1 rounded-full bg-[hsl(210,10%,30%)]" />
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default AppPreview;
