import { useState } from "react";
import { motion } from "framer-motion";
import { Eye, Smartphone, Monitor, Tablet, Code2 } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AppPreviewProps {
  isGenerated: boolean;
  appName: string;
}

type ViewMode = "desktop" | "tablet" | "mobile";

const viewWidths: Record<ViewMode, string> = {
  desktop: "w-full",
  tablet: "w-[768px] max-w-full",
  mobile: "w-[375px] max-w-full",
};

const AppPreview = ({ isGenerated, appName }: AppPreviewProps) => {
  const [viewMode, setViewMode] = useState<ViewMode>("desktop");
  const [showCode, setShowCode] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="sf-glass rounded-2xl p-6"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Eye className="h-5 w-5 text-accent" />
          <h2 className="text-lg font-semibold text-foreground">
            Live Preview
          </h2>
          <Tooltip>
            <TooltipTrigger>
              <span className="text-xs bg-muted text-muted-foreground px-2 py-0.5 rounded-full cursor-help">
                ?
              </span>
            </TooltipTrigger>
            <TooltipContent>
              <p className="max-w-xs text-sm">
                See your app before building. Switch between device sizes to
                test responsiveness.
              </p>
            </TooltipContent>
          </Tooltip>
        </div>

        <div className="flex items-center gap-1 bg-muted rounded-lg p-1">
          {([
            { mode: "desktop" as const, icon: Monitor },
            { mode: "tablet" as const, icon: Tablet },
            { mode: "mobile" as const, icon: Smartphone },
          ]).map(({ mode, icon: Icon }) => (
            <button
              key={mode}
              onClick={() => setViewMode(mode)}
              className={`p-2 rounded-md transition-colors ${
                viewMode === mode
                  ? "bg-card text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              <Icon className="h-4 w-4" />
            </button>
          ))}
          <div className="w-px h-5 bg-border mx-1" />
          <button
            onClick={() => setShowCode(!showCode)}
            className={`p-2 rounded-md transition-colors ${
              showCode
                ? "bg-card text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <Code2 className="h-4 w-4" />
          </button>
        </div>
      </div>

      <div
        className={`mx-auto rounded-xl border border-border overflow-hidden bg-sf-surface-elevated transition-all duration-300 ${viewWidths[viewMode]}`}
      >
        {!isGenerated ? (
          <div className="flex flex-col items-center justify-center h-[400px] text-muted-foreground">
            <Monitor className="h-16 w-16 mb-4 opacity-20" />
            <p className="text-sm">Your app preview will appear here</p>
            <p className="text-xs mt-1 opacity-60">
              Enter an idea and click Generate
            </p>
          </div>
        ) : showCode ? (
          <div className="h-[400px] overflow-auto p-4 bg-sidebar text-sidebar-foreground font-mono text-xs leading-relaxed">
            <pre>{`// ${appName} — Generated by Sirou Factory
// Clean, organized code with full comments

import React from 'react';

/**
 * Main application component
 * Auto-generated with security best practices
 */
const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border p-4">
        <h1 className="text-xl font-bold">${appName}</h1>
      </header>
      <main className="container mx-auto p-6">
        {/* Your app content here */}
      </main>
    </div>
  );
};

export default App;`}</pre>
          </div>
        ) : (
          <div className="h-[400px] flex flex-col">
            <div className="flex items-center gap-2 px-4 py-2 border-b border-border bg-muted/50">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-sf-danger/60" />
                <div className="w-3 h-3 rounded-full bg-sf-caution/60" />
                <div className="w-3 h-3 rounded-full bg-sf-safe/60" />
              </div>
              <span className="text-xs text-muted-foreground ml-2">
                {appName}
              </span>
            </div>
            <div className="flex-1 flex flex-col items-center justify-center p-8">
              <div className="w-full max-w-sm space-y-4">
                <div className="h-8 sf-gradient-bg rounded-lg opacity-80" />
                <div className="h-4 bg-muted rounded w-3/4" />
                <div className="h-4 bg-muted rounded w-1/2" />
                <div className="grid grid-cols-2 gap-3 mt-6">
                  <div className="h-24 bg-muted rounded-xl" />
                  <div className="h-24 bg-muted rounded-xl" />
                </div>
                <div className="h-10 sf-gradient-bg rounded-lg opacity-60 mt-4" />
              </div>
            </div>
          </div>
        )}
      </div>
    </motion.div>
  );
};

export default AppPreview;
