/**
 * Blueprint → Executable Actions Converter
 * Transforms an AppBlueprint into a batch of JSON Actions
 * that the Executor Engine can run to scaffold the entire app.
 */

import type { AppBlueprint } from "@/components/factory/AIPlannerEngine";
import type { ValidatedAction } from "./action-schema";
import { classifyRisk } from "./action-schema";
import type { FactoryAction } from "./action-schema";

// ─── Main Converter ───

export function blueprintToActions(bp: AppBlueprint): ValidatedAction[] {
  const actions: ValidatedAction[] = [];

  const add = (action: FactoryAction, desc: string) => {
    const risk = classifyRisk(action);
    actions.push({
      action,
      risk,
      requiresApproval: risk === "high" || risk === "critical",
      description: desc,
    });
  };

  // 1. Project structure
  add(
    { action: "create_file", path: `src/apps/${slug(bp.appName)}/config.json`, content: JSON.stringify({ name: bp.appName, description: bp.description, theme: bp.theme || "sovereign-dark", hardware: bp.hardwareNeeds || [], plugins: bp.plugins }, null, 2), encoding: "utf-8" },
    `📁 إنشاء مشروع: ${bp.appName}`,
  );

  // 2. Entity/model files
  for (const entity of bp.entities) {
    const typeContent = generateEntityType(entity);
    add(
      { action: "create_file", path: `src/apps/${slug(bp.appName)}/models/${entity.name}.ts`, content: typeContent, encoding: "utf-8" },
      `🗄️ نموذج بيانات: ${entity.name}`,
    );
  }

  // 3. Page/screen files
  for (const page of bp.pages) {
    const pageContent = generatePageComponent(bp.appName, page, bp.theme);
    add(
      { action: "create_file", path: `src/apps/${slug(bp.appName)}/pages/${slug(page.name)}.tsx`, content: pageContent, encoding: "utf-8" },
      `📄 شاشة: ${page.name}`,
    );
  }

  // 4. Router
  add(
    { action: "create_file", path: `src/apps/${slug(bp.appName)}/router.tsx`, content: generateRouter(bp), encoding: "utf-8" },
    `🔀 نظام التنقل`,
  );

  // 5. Feature modules (approved only)
  const approved = bp.features.filter(f => f.approved);
  for (const feature of approved) {
    if (isInfraFeature(feature.name)) continue; // Skip infra features (handled separately)
    add(
      { action: "create_file", path: `src/apps/${slug(bp.appName)}/features/${slug(feature.name)}.ts`, content: generateFeatureModule(feature), encoding: "utf-8" },
      `⚙️ ميزة: ${feature.name}`,
    );
  }

  // 6. Hardware bridge config
  if (bp.hardwareNeeds && bp.hardwareNeeds.length > 0) {
    add(
      { action: "create_file", path: `src/apps/${slug(bp.appName)}/hardware-bridge.ts`, content: generateHardwareBridge(bp.hardwareNeeds), encoding: "utf-8" },
      `📱 جسر الأجهزة: ${bp.hardwareNeeds.join(", ")}`,
    );
  }

  // 7. App entry point
  add(
    { action: "create_file", path: `src/apps/${slug(bp.appName)}/App.tsx`, content: generateAppEntry(bp), encoding: "utf-8" },
    `🚀 نقطة الدخول الرئيسية`,
  );

  // 8. Styles
  add(
    { action: "create_file", path: `src/apps/${slug(bp.appName)}/styles.css`, content: generateStyles(bp), encoding: "utf-8" },
    `🎨 ملف الأنماط`,
  );

  return actions;
}

// ─── Helpers ───

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9\u0600-\u06FF]+/g, "-").replace(/^-|-$/g, "") || "app";
}

function isInfraFeature(name: string): boolean {
  const infra = ["AES-256", "Code-Splitting", "Lazy Loading", "Hardware Bridge", "Permission", "Role-Based", "Splash Screen", "Form Validation", "Error Handling", "Smooth Animations"];
  return infra.some(k => name.includes(k));
}

// ─── Code Generators ───

function generateEntityType(entity: { name: string; fields: string[] }): string {
  const fields = entity.fields.map(f => `  ${f}: ${inferType(f)};`).join("\n");
  const typeName = entity.name.charAt(0).toUpperCase() + entity.name.slice(1).replace(/s$/, "");
  return `/**\n * ${entity.name} — Auto-generated by Sirou Factory\n */\n\nexport interface ${typeName} {\n${fields}\n}\n\nexport type ${typeName}Create = Omit<${typeName}, "id" | "created_at">;\n`;
}

function inferType(field: string): string {
  if (field === "id") return "string";
  if (field.endsWith("_id")) return "string";
  if (field.endsWith("_at") || field.endsWith("_date")) return "string";
  if (field.endsWith("_count") || field === "total" || field === "price" || field === "stock" || field === "rating") return "number";
  if (field.endsWith("_url")) return "string";
  if (field === "available" || field === "read" || field.endsWith("_enabled")) return "boolean";
  if (field === "items") return "string[]";
  if (field === "status") return "'active' | 'inactive' | 'pending'";
  if (field === "role") return "'user' | 'admin'";
  if (field === "priority") return "'low' | 'medium' | 'high'";
  return "string";
}

function generatePageComponent(appName: string, page: { name: string; route: string; components: string[] }, theme?: any): string {
  const components = page.components.map(c => `        <div className="sf-glass-subtle rounded-xl p-4">\n          <h3 className="text-sm font-semibold text-foreground mb-2">${c}</h3>\n          <p className="text-xs text-muted-foreground">${c} component placeholder</p>\n        </div>`).join("\n");

  return `/**\n * ${page.name} — ${appName}\n * Route: ${page.route}\n */\n\nimport { motion } from "framer-motion";\n\nconst ${page.name.replace(/[^a-zA-Z]/g, "")}Page = () => {\n  return (\n    <motion.div\n      initial={{ opacity: 0, y: 10 }}\n      animate={{ opacity: 1, y: 0 }}\n      className="p-4 space-y-4"\n    >\n      <h2 className="text-lg font-bold text-foreground">${page.name}</h2>\n      <div className="grid gap-3">\n${components}\n      </div>\n    </motion.div>\n  );\n};\n\nexport default ${page.name.replace(/[^a-zA-Z]/g, "")}Page;\n`;
}

function generateRouter(bp: AppBlueprint): string {
  const imports = bp.pages.map(p => {
    const name = p.name.replace(/[^a-zA-Z]/g, "");
    return `import ${name}Page from "./pages/${slug(p.name)}";`;
  }).join("\n");

  const routes = bp.pages.map(p => {
    const name = p.name.replace(/[^a-zA-Z]/g, "");
    return `  { path: "${p.route}", component: ${name}Page, name: "${p.name}" },`;
  }).join("\n");

  return `/**\n * Router — ${bp.appName}\n */\n\n${imports}\n\nexport const routes = [\n${routes}\n];\n\nexport type AppRoute = typeof routes[number];\n`;
}

function generateFeatureModule(feature: { name: string; category: string }): string {
  return `/**\n * Feature: ${feature.name}\n * Category: ${feature.category}\n * Auto-generated by Sirou Factory\n */\n\nexport const featureConfig = {\n  name: "${feature.name}",\n  category: "${feature.category}",\n  enabled: true,\n};\n\nexport function init${feature.name.replace(/[^a-zA-Z]/g, "")}() {\n  console.log("[${feature.name}] initialized");\n}\n`;
}

function generateHardwareBridge(hardware: string[]): string {
  const imports = hardware.map(h => {
    switch (h) {
      case "Camera": return `import { requestCamera } from "@/lib/hardware/camera";`;
      case "GPS": return `import { requestLocation } from "@/lib/hardware/location";`;
      case "Notifications": return `import { requestNotificationPermission } from "@/lib/hardware/notifications";`;
      default: return `// ${h} — manual integration required`;
    }
  }).join("\n");

  const inits = hardware.map(h => `  "${h}": { available: true, initialized: false },`).join("\n");

  return `/**\n * Hardware Bridge — Auto-configured\n */\n\n${imports}\n\nexport const hardwareStatus: Record<string, { available: boolean; initialized: boolean }> = {\n${inits}\n};\n\nexport async function initHardware() {\n  console.log("[HardwareBridge] Initializing ${hardware.length} modules...");\n}\n`;
}

function generateAppEntry(bp: AppBlueprint): string {
  return `/**\n * ${bp.appName} — Main Entry\n * Generated by Sirou Factory\n */\n\nimport { routes } from "./router";\n\nexport const appConfig = {\n  name: "${bp.appName}",\n  description: "${bp.description.slice(0, 100)}",\n  routes,\n  features: ${JSON.stringify(bp.features.filter(f => f.approved).map(f => f.name))},\n  hardware: ${JSON.stringify(bp.hardwareNeeds || [])},\n  plugins: ${JSON.stringify(bp.plugins)},\n};\n\nexport default appConfig;\n`;
}

function generateStyles(bp: AppBlueprint): string {
  const primary = bp.theme?.primary || "#D4AF37";
  const bg = bp.theme?.background || "#0A0A0F";
  return `/* ${bp.appName} — Auto-generated styles */\n\n.app-${slug(bp.appName)} {\n  --app-primary: ${primary};\n  --app-background: ${bg};\n}\n`;
}
